USE [master]
GO
/****** Object:  Database [LoginRegistration]    Script Date: 2/2/2022 7:05:25 AM ******/
CREATE DATABASE [LoginRegistration]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LoginRegistration', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LoginRegistration.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LoginRegistration_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LoginRegistration_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LoginRegistration].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LoginRegistration] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LoginRegistration] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LoginRegistration] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LoginRegistration] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LoginRegistration] SET ARITHABORT OFF 
GO
ALTER DATABASE [LoginRegistration] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LoginRegistration] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LoginRegistration] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LoginRegistration] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LoginRegistration] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LoginRegistration] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LoginRegistration] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LoginRegistration] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LoginRegistration] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LoginRegistration] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LoginRegistration] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LoginRegistration] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LoginRegistration] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LoginRegistration] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LoginRegistration] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LoginRegistration] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LoginRegistration] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LoginRegistration] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LoginRegistration] SET  MULTI_USER 
GO
ALTER DATABASE [LoginRegistration] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LoginRegistration] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LoginRegistration] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LoginRegistration] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [LoginRegistration] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LoginRegistration] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [LoginRegistration] SET QUERY_STORE = OFF
GO
ALTER DATABASE [LoginRegistration] SET  READ_WRITE 
GO
ALTER DATABASE [LoginRegistration] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LoginRegistration].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LoginRegistration] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LoginRegistration] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LoginRegistration] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LoginRegistration] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LoginRegistration] SET ARITHABORT OFF 
GO
ALTER DATABASE [LoginRegistration] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LoginRegistration] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [LoginRegistration] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LoginRegistration] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LoginRegistration] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LoginRegistration] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LoginRegistration] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LoginRegistration] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LoginRegistration] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LoginRegistration] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LoginRegistration] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LoginRegistration] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LoginRegistration] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LoginRegistration] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LoginRegistration] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LoginRegistration] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LoginRegistration] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LoginRegistration] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LoginRegistration] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LoginRegistration] SET  MULTI_USER 
GO
ALTER DATABASE [LoginRegistration] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LoginRegistration] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LoginRegistration] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LoginRegistration] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [LoginRegistration]
GO
/****** Object:  Table [dbo].[RegisterUser]    Script Date: 7/16/2018 7:45:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RegisterUser](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](100) NOT NULL,
	[LastName] [varchar](100) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Password] [varchar](500) NOT NULL,
 CONSTRAINT [PK_RegisterUser] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[RegisterUser] ON 

INSERT [dbo].[RegisterUser] ([Id], [FirstName], [LastName], [Email], [Password]) VALUES (1, N'Test', N'Lastname', N'test@test.com', N'Test123')
SET IDENTITY_INSERT [dbo].[RegisterUser] OFF
USE [master]
GO
ALTER DATABASE [LoginRegistration] SET  READ_WRITE 
GO